# Generated by Django 5.2.7 on 2025-10-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.CharField()),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('password', models.CharField()),
            ],
        ),
    ]
