# Generated by Django 5.2.7 on 2025-10-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_allproducts_alter_farmer_mobile_alter_users_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='id',
        ),
        migrations.AddField(
            model_name='farmer',
            name='fid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
