# Generated by Django 5.2.7 on 2025-10-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('village', models.CharField(max_length=100)),
                ('aadharno', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
