# Generated by Django 5.2.7 on 2025-10-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('farmer_location', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=300)),
                ('cultivated_date', models.DateTimeField()),
                ('experiry_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='farmer',
            name='mobile',
            field=models.PositiveIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
