# Generated by Django 5.2.7 on 2025-10-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_farmer_id_farmer_fid'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='fid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
