# Generated by Django 5.2.7 on 2025-10-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_allproducts_fid'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='photo',
            field=models.ImageField(default='product/default.jpg', upload_to='product/'),
        ),
    ]
